// enums.js

const USER_CATEGORIES = [
  "ADMIN",
  "SCHOOL_STUDENT",
  "UNDERGRADUATE",
  "GRADUATE",
  "COUNSELLOR",
];

const ROLES = {
  ADMIN: "ADMIN",
  SCHOOL_STUDENT: "SCHOOL_STUDENT",
  UNDERGRADUATE: "UNDERGRADUATE",
  GRADUATE: "GRADUATE",
  COUNSELLOR: "COUNSELLOR",
}

module.exports = {
  USER_CATEGORIES,
  ROLES,
};
